import { ChakraProvider } from '@chakra-ui/react';
import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import { RoleProvider } from './providers/RoleContext';
import Sidebar from '@/components/global/Sidebar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ChakraProvider>
        <RoleProvider>
          <main>
          {children}
          </main>
        </RoleProvider>
      </ChakraProvider>
      </body>
    </html>
  );
}
